{"name": "test_case4", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_case4():\n        print('test_case4')\n>       assert False\nE       assert False\n\ntest_allure02.py:22: AssertionError"}, "attachments": [{"name": "stdout", "source": "ea584a2e-a110-45db-8b45-e8fd948cd59a-attachment.txt", "type": "text/plain"}], "start": 1629203534064, "stop": 1629203534064, "uuid": "4e17a9a4-e293-4b87-b3cf-3b139dbf9f53", "historyId": "0d0e8a3ee1a68b31a1f638e7df56ecd5", "testCaseId": "fc1ae45a3411fec390f6555159eb4f8f", "fullName": "test_allure02#test_case4", "labels": [{"name": "suite", "value": "test_allure02"}, {"name": "host", "value": "HSZC1712-0006"}, {"name": "thread", "value": "3896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure02"}]}